name: Integration Tests

on:
  workflow_run:
    workflows: ["Unit Tests"]
    types:
      - completed

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install uv
      uses: astral-sh/setup-uv@v4
      
    - name: Install Terraform
      uses: hashicorp/setup-terraform@v3
      
    - name: Deploy test environment
      run: make deploy-test-env
      env:
        AWS_REGION: eu-central-1
        AWS_LAMBDA_NAME: test-lambda
        
    - name: Run integration tests
      run: make test-integration
      
    - name: Cleanup
      if: always()
      run: make destroy-test-env
